[project]
name = "CellularAutomats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pyqt-tools>=1.0.0",
    "pyqt6>=6.9.1",
]
